[package]
name = "tsp-rust"
version = "0.1.0"
authors = ["Matthew K <mattjk@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = {version="0.8.0", features=["std"]}
